config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'user_book/index'
  get 'book/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'book#index'
  get 'libros/todos', to: "book#index"
  get 'libros/mis_libros_1', to: "userbook#index"
  get 'libros/mis_libros', to: "user#index"
  post 'libros/agregar_libro', to: "book#add_book_to_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    has_many :userbooks
    has_many :users, through: :userbooks
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :stocks 
    has_many :store, through: :stocks 
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :product
    belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :stocks 
    has_many :products, through: :stocks 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :userbooks
  has_many :books, through: :userbooks
end

app/models/userbook.rb
class Userbook < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  before_action :authenticate_user!
  def index
    @books=Book.all
  end
  def add_book_to_user
    b=params.require(:book).permit(:id)
    book= Book.find(b[:id])
    unless book.nil?
      current_user.books.push(book)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    def index
      @products=Product.all
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
end

app/controllers/user_book_controller.rb
class UserBookController < ApplicationController
  def index
    @userBook=Userbook.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
    @userBook=current_user.books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/user_book_helper.rb
module UserBookHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/book/index.html.erb
<div class="jumbotron text-center">
        <h1>Libros</h1>
        <p>Coleccion de libros</p>
    </div>
    
    
    <ul class="list-group">
        <% for book in @books %>
            <li class="list-group-item">
                <%= book.name %>
                <p>Fecha: <%= book.created_at %></p>
                <form class="form-group" method="POST" action="<%= libros_agregar_libro_path%>">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <input type="hidden" name="book[id]" value="<%= book.id %>">
                    <button type="submit" class="btn btn-primary">Agregar a mis libros</button>
                </form>
            </li>
            <% end %>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Proyecto1</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"
            crossorigin="anonymous">
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">LIBROS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= libros_todos_path %>">Libreria
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=  libros_mis_libros_path %>">Mis Libros
            </a>
          </li>
          <% end %>
            <% if !user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_registration_path %>">Registrarme</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
              </li>
              <% end %>
      </ul>
      <ul class="navbar-nav fl">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link">
              <span>
                <%= current_user.email %>
              </span>
            </a>

          </li>
          <li class="nav-item">
            <a class="nav-link" data-method="delete" href="<%= destroy_user_session_path %>">Cerrar Sesion
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <% end %>
      </ul>
    </div>
  </nav>
  <%= yield %>
    <div class="notice">
      <%= notice %>
    </div>
    <div class="alert">
      <%= alert %>
    </div>
</body>

</html>

app/views/products/index.html.erb
<div class="jumbotron text-center">
    <h1>Hola Mundo</h1>
    <p>Funciona</p>
</div>


<ul class="list-group">
    <% for product in @products %>
        <li class="list-group-item">
            <%= product.name %>
            <ul class="list-group">
                <% for store in product.store %>
                <li class="list-group-item">
                    <%= store.name%>
                </li>
                <% end%>
            </ul>
        </li>
        <% end %>
</ul>

app/views/user/index.html.erb
<div class="jumbotron text-center">
        <h1>Libros del Usuario</h1>
        <p>Coleccion de libros del Usuario</p>
    </div>
    
    
    <ul class="list-group">
        <% for book in @userBook %>
            <li class="list-group-item">
                <%= book.name %>
                <p>Fecha: <%= book.created_at %></p>
                <!-- <form class="form-group" method="POST" action="<%= libros_agregar_libro_path%>">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <input type="hidden" name="book[id]" value="<%= book.id %>">
                    <button type="submit" class="btn btn-primary">Agregar a mis libros</button>
                </form> -->
            </li>
            <% end %>
    </ul>

app/views/user_book/index.html.erb
<div class="jumbotron text-center">
        <h1>Libros del Usuario</h1>
        <p>Coleccion de libros del Usuario</p>
    </div>
    
    
    <ul class="list-group">
        <% for book in @userBook %>
            <li class="list-group-item">
                <%= book.name %>
                <!-- <form class="form-group" method="POST" action="<%= libros_agregar_libro_path%>">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <input type="hidden" name="book[id]" value="<%= book.id %>">
                    <button type="submit" class="btn btn-primary">Agregar a mis libros</button>
                </form> -->
            </li>
            <% end %>
    </ul>